# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rustgoslin_wrappers", use_symbols = TRUE, package_name = "rustgoslin")

#' @usage NULL
#' @useDynLib rustgoslin, .registration = TRUE
NULL

#' Return sum formula for provided element table.
#' @export
compute_sum_formula <- function(et) .Call(wrap__compute_sum_formula, et)

#' Return mass for provided element table.
#' @export
compute_mass <- function(et) .Call(wrap__compute_mass, et)


# nolint end
